export enum SubGroup {
  UNKNOWN = 'UNKNOWN',
  BUSINESS = 'BUSINESS',
  COMPOSITES = 'COMPOSITES',
  MECHANICAL = 'MECHANICAL',
  ELECTRICAL = 'ELECTRICAL',
  AUTONOMOUS = 'AUTONOMOUS',
  RACE_TEAM = 'RACE_TEAM'
}