export * from './ping.controller';
export * from './member.controller';
export * from './alumni.controller';
export * from './sponsor.controller';
export * from './login.controller';
export * from './register.controller';
export * from './job.controller';
export * from './activation.controller';
export * from './verification.controller';