on:
  pull_request:
    branches:
      - '**'
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'web/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Change directory to web
        run: cd web
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
