name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for Node projects)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies (web)
        working-directory: ./web
        run: npm ci

      - name: Build project (web)
        working-directory: ./web
        run: npm run build

      - name: Install dependencies (api)
        working-directory: ./api
        run: npm ci

      - name: Build project (api)
        working-directory: ./api
        run: npm run build
