name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for Node projects)
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Choose your node version

      - name: Install dependencies (web)
        working-directory: ./web
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build project (web)
        working-directory: ./web
        run: yarn build

      - name: Install dependencies (api)
        working-directory: ./api
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build project (api)
        working-directory: ./api
        run: yarn build
